kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2
      id: "2"
  template:
    metadata:
      labels:
        app: kafka2
        id: "2"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka2-service
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_BROKER_ID
              value: "2"
            # - name: KAFKA_NUM_PARTITIONS
            #   value: "7"
            # - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            #   value: "3"
            - name: KAFKA_CREATE_TOPICS
              value: "topic:5:3"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2-service
  labels:
    name: kafka2
spec:
  ports:
    - name: kafka2-port
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: kafka2
    id: "2"
